# Generated by Django 4.2.4 on 2023-08-13 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanningApp', '0003_property_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rootNumber',
        ),
    ]
