# Generated by Django 4.2.4 on 2023-08-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanningApp', '0004_remove_property_rootnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
