# Generated by Django 4.2.4 on 2023-08-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanningApp', '0007_message_descriptionhighprofanity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='profanityFlag',
            field=models.BooleanField(default=False),
        ),
    ]
