# Generated by Django 4.2.4 on 2023-08-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanningApp', '0008_message_profanityflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='claimerFlag',
            field=models.BooleanField(default=False),
        ),
    ]
